
name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-Linux:
    name: Build on Linux
    strategy:
      matrix:
        rust:
          - stable
          - beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Install libclang-dev
        run: |
          sudo apt-get update
          sudo apt-get install libclang-dev
      - name: Cargo build
        run: cargo build --no-default-features
      - name: Cargo clippy
        run: cargo clippy --no-default-features --tests -- --deny warnings
  build-macOS:
    name: Build on macOS
    strategy:
      matrix:
        rust:
          - stable
          - beta
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Cargo build
        run: cargo build
      - name: Cargo clippy
        run: cargo clippy --tests -- --deny warnings
  build-Windows:
    name: Build on Windows
    strategy:
      matrix:
        rust:
          - stable
          - beta
    runs-on: windows-latest
    steps:
      - name: Install nasm
        run: choco install nasm
      - name: Install ninja
        run: choco install ninja
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Cargo build
        run: cargo build
      - name: Cargo clippy
        run: cargo clippy --tests -- --deny warnings

